-- MySQL Script generated by MySQL Workbench
-- Tue May 23 02:05:26 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`manager` (
  `manager_id` INT(10) NOT NULL,
  `manager_password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`manager_id`),
  UNIQUE INDEX `id_UNIQUE` (`manager_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `user_id` VARCHAR(255) NOT NULL,
  `user_password` VARCHAR(255) NOT NULL,
  `age` INT(5) NOT NULL,
  `sex` VARCHAR(10) NOT NULL,
  `password_question` VARCHAR(255) NOT NULL,
  `password_answer` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_name_UNIQUE` (`user_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`note_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`note_info` (
  `note_id` INT(10) NOT NULL,
  `title` VARCHAR(255) NULL,
  `content` VARCHAR(255) NULL,
  `create_time` DATETIME NULL,
  `note_user_id` VARCHAR(255) NULL,
  `top` TINYINT NULL,
  `count` INT(10) NULL,
  `note_picture` VARCHAR(255) NULL,
  PRIMARY KEY (`note_id`),
  UNIQUE INDEX `note_id_UNIQUE` (`note_id` ASC),
  INDEX `user_id_idx` (`note_user_id` ASC),
  CONSTRAINT `user_id`
    FOREIGN KEY (`note_user_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`web_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`web_info` (
  `url` VARCHAR(255) NOT NULL,
  `web_title` VARCHAR(255) NULL,
  `web_keyword` VARCHAR(255) NULL,
  `web_content` VARCHAR(255) NULL,
  `web_updatetime` DATETIME NULL,
  `style_category` VARCHAR(255) NULL,
  `age_category` VARCHAR(255) NULL,
  PRIMARY KEY (`url`),
  UNIQUE INDEX `url_UNIQUE` (`url` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`browse_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`browse_record` (
  `bro_user_id` VARCHAR(255) NOT NULL,
  `bro_note_id` INT(10) NULL,
  `browse_time` DATETIME NULL,
  `bro_url` VARCHAR(255) NULL,
  PRIMARY KEY (`bro_user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`bro_user_id` ASC),
  INDEX `url_idx` (`bro_url` ASC),
  INDEX `note_id_idx` (`bro_note_id` ASC),
  CONSTRAINT `user_id`
    FOREIGN KEY (`bro_user_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `note_id`
    FOREIGN KEY (`bro_note_id`)
    REFERENCES `mydb`.`note_info` (`note_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `url`
    FOREIGN KEY (`bro_url`)
    REFERENCES `mydb`.`web_info` (`url`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_collection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_collection` (
  `coll_user_id` VARCHAR(255) NOT NULL,
  `coll_note_id` INT(10) NULL,
  PRIMARY KEY (`coll_user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`coll_user_id` ASC),
  INDEX `note_id_idx` (`coll_note_id` ASC),
  CONSTRAINT `user_id`
    FOREIGN KEY (`coll_user_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `note_id`
    FOREIGN KEY (`coll_note_id`)
    REFERENCES `mydb`.`note_info` (`note_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`search_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`search_record` (
  `search_keyword` VARCHAR(255) NOT NULL,
  `url` VARCHAR(255) NULL,
  `search_time` DATETIME NULL,
  PRIMARY KEY (`search_keyword`),
  UNIQUE INDEX `search_keyword_UNIQUE` (`search_keyword` ASC),
  INDEX `url_idx` (`url` ASC),
  CONSTRAINT `url`
    FOREIGN KEY (`url`)
    REFERENCES `mydb`.`web_info` (`url`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reply_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reply_info` (
  `reply_note_id` INT(10) NOT NULL,
  `operate_time` DATETIME NULL,
  `content` VARCHAR(255) NULL,
  `reply_user_id` VARCHAR(255) NULL,
  PRIMARY KEY (`reply_note_id`),
  UNIQUE INDEX `note_id_UNIQUE` (`reply_note_id` ASC),
  INDEX `user_id_idx` (`reply_user_id` ASC),
  CONSTRAINT `note_id`
    FOREIGN KEY (`reply_note_id`)
    REFERENCES `mydb`.`note_info` (`note_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_id`
    FOREIGN KEY (`reply_user_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
